Affichage des équipes finales éliminées
mbernardeau/euro-2021 pull request #143
Opened 2021-04-17 21:07 UTC by naustra

Rajout d'une colonne dans le classement pour afficher ceux dont l'équipe principale a été révélée

2021-04-17 21:27 UTC, naustra commented
Apriori ça marche, mais j'aimerais ton avis sur la sécurité que j'ai allégé pour la collection 'opponents'.

C'est pas trop pressé mais je suis curieux de voir qui a son vainqueur éliminé comme même ^^

2021-04-19 18:29 UTC, mbernardeau requested changes

2021-04-19 18:29 UTC, mbernardeau commented on src/screens/Ranking/GroupRanking/GroupRanking.jsx
> +  const imgUrl = memoize(() => require(`../../../assets/icons/mask6.png`))
Si url constante, importe là au dessus du fichier pour éviter de le faire à chaque rendu.

```suggestion
import imgUrl from '../../../assets/icons/mask6.png'
```

2021-04-19 18:29 UTC, mbernardeau commented on src/screens/Ranking/GroupRanking/GroupRanking.jsx
> +                        alt="unknown team"
Un bon texte alternatif remplace l'image (si indisponible pour des raisons techniques ou pour déficient visuel), donc il faudrait mettre le nom de l'équipe je pense

2021-04-19 18:29 UTC, mbernardeau commented on src/screens/Ranking/GroupRanking/GroupRanking.jsx
> +                      ></img>
Pas d'enfants => Balise auto-fermante
```suggestion
                      />
```

2021-04-19 18:29 UTC, mbernardeau commented on src/firebase/rules/firestore.rules
> +        request.auth.uid == request.resource.data.uid;
Il faudrait éviter que cette collection puisse être écrite, il s'agit d'une vue "publique" d'autres données. Il faudrait plutôt que l'utilisateur puisse écrire dans son document `user` et que la fonction `onUserUpdate` se charge de mettre à jour la collection `opponents` (comme c'est déjà le cas pour le nom, photo de profile...).

2021-04-19 18:32 UTC, naustra commented on src/screens/Ranking/GroupRanking/GroupRanking.jsx
> +                        alt="unknown team"
Heu bah non justement, on utilise cette image là quand l'équipe n'est pas éliminée donc il ne faut pas la dévoiler.

2021-04-19 18:33 UTC, naustra commented on src/screens/Ranking/GroupRanking/GroupRanking.jsx
> +                        alt="unknown team"
Mais ok, je vois l'idée !

2021-04-19 18:34 UTC, mbernardeau commented on src/screens/Ranking/GroupRanking/GroupRanking.jsx
> +                        alt="unknown team"
Ah pardon mal compris, dans ce cas: `Équipe non éliminée` ?

2021-04-19 21:11 UTC, merged