tribues
mbernardeau/euro-2021 pull request #165
Opened 2021-05-03 15:59 UTC by naustra

Closes #101
Closes #156

2021-05-03 20:05 UTC, naustra commented
Rajouter adresse pour envois chèques

2021-05-03 20:36 UTC, mbernardeau requested changes

2021-05-03 20:36 UTC, mbernardeau commented on src/screens/Groups/CreateGroup/CreateGroup.jsx
> +        PAM doit être entre 20% et 80%.
Le reste sert à faire des lots pour les gagnants ?
Peut-être le préciser ici pour que ce soit un peu plus clair ?

2021-05-03 20:36 UTC, mbernardeau commented on src/firebase/rules/firestore.rules
> +        request.resource.data.percent is number &&
Cette règle ne risque pas de bloquer le cas des tribus gratuites ? J'imagine que dans ce cas on ne devrait pas enregistrer de pourcentage ?

2021-05-09 08:53 UTC, naustra commented
Ajouter addresse pour les chèques également

2021-05-09 10:37 UTC, naustra commented on src/firebase/rules/firestore.rules
> +        request.resource.data.percent is number &&
Je sais que c'est pas le must. Je pense qu'il faudrait même afficher le pourcentage seulement si le prix n'est pas nul mais ça ne pose pas trop de problème comme ça je pense.

2021-05-10 21:58 UTC, merged