Schedule save
mbernardeau/euro-2021 pull request #211
Opened 2021-05-19 15:41 UTC by naustra

Closes #74

2021-05-19 15:43 UTC, naustra commented
J'ai fait ça mais j'ai des questions en fait si t'as un moment !

2021-06-07 15:51 UTC, mbernardeau requested changes

2021-06-07 15:51 UTC, mbernardeau commented on functions/src/saveData.js
> +  .schedule('every 24 hours')
Attention avec le `every 24 hours`, ce sera relatif à la date du dernier déploiement donc assez imprédictible.

Mieux vaut utiliser une truc comme `59 23 * * *` (tous les jours à 23h59).

2021-06-07 15:51 UTC, mbernardeau commented on functions/src/saveData.js
> +  .onRun((context) => {
Ajoute `.timeZone('Europe/Paris')` sinon les heures programmées ne le seront pas forcément dans la time zone de France.

2021-06-07 21:27 UTC, naustra reviewed
J'ai fait les changements

2021-06-09 09:59 UTC, mbernardeau approved these changes

2021-06-09 10:04 UTC, merged